project:
  type: book
  output-dir: "output_html"
  
lightbox: true

book:
  title: "GIS in Public Health: R"
  author: "Val Stacey"
  date: "1/12/2026"
  reader-mode: false
  
  sidebar:
    collapse-level: 2
    style: "docked"
    
  chapters:
    - index.qmd
    - part: Introduction to GIS
      chapters:
      - chapters/1a_GIS_Structure.qmd
      - chapters/1b_Projections.qmd
      - chapters/1c_ChoosingCRS.qmd
      - chapters/1d_Privacy.qmd
      - chapters/1e_Bias.qmd
    
    - part: Types of Spatial Data
      chapters:
      - chapters/2a_ShapefileComps.qmd
      - chapters/2b_Points.qmd
      - chapters/2c_Rasters.qmd

    
    - part: Map Basics
      chapters:
        - chapters/3a_MapParts.qmd
        - chapters/3b_Choropleths.qmd
        - chapters/3c_Choropleth_Alts.qmd
        - chapters/3d_Color.qmd
        - chapters/3e_ColorPalettes.qmd
        
    - part: Maps from APIs
      chapters:
        - chapters/4a_census_data.qmd       
    
    
    - part: Interactive Maps
      chapters: 
        - chapters/5a_leaflet.qmd
        - chapters/5b_integrate_shiny.qmd
        
        
  appendices:
    - chapters/zz_sf_references.qmd
     

execute:
  rscript: "C:\\Program Files\\R\\R-4.4.0\\bin\\x64"
  eval: TRUE
  warning: FALSE
  message: FALSE
  
bibliography: references.bib

format:
  html:
    theme: cosmo
    css: "styles.css"
    number-sections: true
    number-depth: 1
    code-summary: "Show the code"
    code-copy: true
    code-overflow: wrap
    highlight-style: "custom-theme.json"
    code-block-border-left: "#3DB4ADFF"
    link-external-newwindow: true
    toc: FALSE
    code-tools:
      source: true
      toggle: false
      caption: none

